# Generated by Django 4.2.9 on 2026-01-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('source', models.CharField(default='google_drive', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('google_drive_id', models.CharField(max_length=100, unique=True)),
                ('size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_path', models.URLField()),
                ('source', models.CharField(default='google_drive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['google_drive_id'], name='importer_im_google__506745_idx'), models.Index(fields=['source'], name='importer_im_source_8d6abf_idx'), models.Index(fields=['created_at'], name='importer_im_created_571ff8_idx')],
            },
        ),
    ]
